name: Build

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.6.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Build
        run: poetry build
      - name: Create token and credentials
        run: |
          echo "${{ secrets.TOKEN_JSON }}" > token.json
          echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json
      - name: Build
        run: poetry run python -m supernote_kathimerini
